In [22]:
import pandas as pd
from sqlalchemy import create_engine
import secret

In [23]:
# Import list of 10,000 fastfood restaurants across United States:

file = "Resources/FastFoodRestaurants.csv"
fastfood_df = pd.read_csv(file)
fastfood_df.head()

,address,city,country,keys,latitude,longitude,name,postalCode,province,websites
0,324 Main St,Massena,US,us/ny/massena/324mainst/-1161002137,44.92130,-74.89021,McDonald's,13662,NY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
1,530 Clinton Ave,Washington Court House,US,us/oh/washingtoncourthouse/530clintonave/-7914...,39.53255,-83.44526,Wendy's,43160,OH,http://www.wendys.com
2,408 Market Square Dr,Maysville,US,us/ky/maysville/408marketsquaredr/1051460804,38.62736,-83.79141,Frisch's Big Boy,41056,KY,"http://www.frischs.com,https://www.frischs.com..."
3,6098 State Highway 37,Massena,US,us/ny/massena/6098statehighway37/-1161002137,44.95008,-74.84553,McDonald's,13662,NY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
4,139 Columbus Rd,Athens,US,us/oh/athens/139columbusrd/990890980,39.35155,-82.09728,OMG! Rotisserie,45701,OH,"http://www.omgrotisserie.com,http://omgrotisse..."

In [24]:
# Establish connection to PostgresSQL fast_food_db:

engine = create_engine(f"postgresql://{secret.user_pass}@localhost:5432/fast_food_db")

In [25]:
# Push fastfood_df to database under table name: fastfood:

fastfood_df.to_sql(name='fastfood', con=engine, if_exists='append', index=False)

In [26]:
fastfood_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
address       10000 non-null object
city          10000 non-null object
country       10000 non-null object
keys          10000 non-null object
latitude      10000 non-null float64
longitude     10000 non-null float64
name          10000 non-null object
postalCode    10000 non-null object
province      10000 non-null object
websites      9535 non-null object
dtypes: float64(2), object(8)
memory usage: 781.3+ KB

In [27]:
# Within the list of 10,000 fastfood resturants, drop ones that are located in DC (because it's not a "state"):

idx_to_drop=fastfood_df[fastfood_df["province"]=="DC"].index
fastfood_df.drop(idx_to_drop,inplace=True)
fastfood_df

,address,city,country,keys,latitude,longitude,name,postalCode,province,websites
0,324 Main St,Massena,US,us/ny/massena/324mainst/-1161002137,44.921300,-74.890210,McDonald's,13662,NY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
1,530 Clinton Ave,Washington Court House,US,us/oh/washingtoncourthouse/530clintonave/-7914...,39.532550,-83.445260,Wendy's,43160,OH,http://www.wendys.com
2,408 Market Square Dr,Maysville,US,us/ky/maysville/408marketsquaredr/1051460804,38.627360,-83.791410,Frisch's Big Boy,41056,KY,"http://www.frischs.com,https://www.frischs.com..."
3,6098 State Highway 37,Massena,US,us/ny/massena/6098statehighway37/-1161002137,44.950080,-74.845530,McDonald's,13662,NY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
4,139 Columbus Rd,Athens,US,us/oh/athens/139columbusrd/990890980,39.351550,-82.097280,OMG! Rotisserie,45701,OH,"http://www.omgrotisserie.com,http://omgrotisse..."
5,4182 Tonya Trl,Hamilton,US,us/oh/hamilton/4182tonyatrl/-1055723171,39.417600,-84.476410,Domino's Pizza,45011,OH,"https://www.dominos.com/en/?redirect=homepage,..."
6,590 S Main St,Englewood,US,us/oh/englewood/590smainst/-1055723171,39.869690,-84.293580,Domino's Pizza,45322,OH,https://www.dominos.com/en/?redirect=homepagea...
7,401 N Jennings St,Saluda,US,us/sc/saluda/401njenningsst/-1161002137,34.005980,-81.770400,McDonald's,29138,SC,http://www.mcdonalds.com
8,205 W Church St,Batesburg,US,us/sc/batesburg/205wchurchst/-791445730,33.913350,-81.533300,Wendy's,29006,SC,http://www.wendys.com
9,2711 W. Kings Highway Ste. 18,Paragould,US,us/ar/paragould/2711wkingshighwayste18/-66712705,36.061070,-90.523250,Pizza Hut,72450,AR,http://www.pizzahut.com
10,613 W Center St,Sheridan,US,us/ar/sheridan/613wcenterst/1780593795,34.306870,-92.407840,SONIC Drive In,72150,AR,https://locations.sonicdrivein.com/ar/sheridan...
11,512 Highway 425 S Lot B,Monticello,US,us/ar/monticello/512highway425slotb/-1055723171,33.619370,-91.802320,Domino's Pizza,71655,AR,"https://www.dominos.com/en/?redirect=homepage,..."
12,1535 NW 50th St,Oklahoma City,US,us/ok/oklahomacity/1535nw50thst/-1161002137,35.522340,-97.538200,McDonald's,73118,OK,"http://mcdonalds.com,http://www.mcdonalds.com/..."
13,125 Towne Center Dr,Lexington,US,us/ky/lexington/125townecenterdr/-1055723171,38.067530,-84.530430,Domino's Pizza,40511,KY,https://www.dominos.com/en/?redirect=homepagea...
14,66 14th St.,Tell City,US,us/in/tellcity/6614thst/1516016543,37.941032,-86.762115,Long John Silver's,47586,IN,http://www.ljsilvers.com
15,301 University Blvd,Louisville,US,us/ky/louisville/301universityblvd/-1161002137,38.219990,-85.764824,McDonald's,40208,KY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
16,5812 NW Expressway,Oklahoma City,US,us/ok/oklahomacity/5812nwexpressway/-1161002137,35.548150,-97.617170,McDonald's,73132,OK,"http://mcdonalds.com,http://www.mcdonalds.com/..."
17,101 Thomas Garst Ln,Leland,US,us/nc/leland/101thomasgarstln/-864103396,34.233890,-77.995440,Taco Bell,28451,NC,"http://www.tacobell.com,https://locations.taco..."
18,1111 New Pointe Blvd,Leland,US,us/nc/leland/1111newpointeblvd/-1161002137,34.211880,-78.024540,McDonald's,28451,NC,"http://mcdonalds.com,http://www.mcdonalds.com/..."
19,782 Old Hickory Blvd Ste 120,Brentwood,US,us/tn/brentwood/782oldhickoryblvdste120/-72295...,36.042220,-86.779950,Qdoba Mexican Grill,37027,TN,"http://www.qdoba.com,https://locations.qdoba.c..."
20,108 Village Rd NE,Leland,US,us/nc/leland/108villagerdne/-1161002137,34.234477,-78.000649,McDonald's,28451,NC,"http://mcdonalds.com,http://www.mcdonalds.com/..."
21,1116 Old Highway 60,Hardinsburg,US,us/ky/hardinsburg/1116oldhighway60/-1161002137,37.792641,-86.492762,McDonald's,40143,KY,"http://mcdonalds.com,http://www.mcdonalds.com/..."
22,1423 Southwest Pkwy,Wichita Falls,US,us/tx/wichitafalls/1423southwestpkwy/-1161002137,33.853710,-98.500650,McDonald's,76302,TX,http://www.mcdonalds.com/?cid=RF:YXT_FM:TP::Ye...
23,908 Padre Blvd,South Padre Island,US,us/tx/southpadreisland/908padreblvd/-1161002137,26.091050,-97.164300,McDonald's,78597,TX,http://www.mcdonalds.com/?cid=RF:YXT_FM:TP::Ye...
24,1131n N Main St,Miami,US,us/ok/miami/1131nnmainst/-1161002137,36.888260,-94.877660,McDonald's,74354,OK,http://www.mcdonalds.com/?cid=RF:YXT_FM:TP::Ye...
25,3401 Hwy 165 North,Pineville,US,us/la/pineville/3401hwy165north/-66712705,31.362600,-92.413430,Pizza Hut,71360,LA,http://www.pizzahut.com
26,1631 E Madison Ave,Bastrop,US,us/la/bastrop/1631emadisonave/1780593795,32.779920,-91.894770,Sonic Drive-In,71220,LA,https://locations.sonicdrivein.com/la/bastrop/...
27,301 S Lynn Riggs Blvd,Claremore,US,us/ok/claremore/301slynnriggsblvd/-1055723171,36.310690,-95.617590,Domino's Pizza,74017,OK,"https://www.dominos.com/en/?redirect=homepage,..."
28,601 E Lincolnway,Minerva,US,us/oh/minerva/601elincolnway/-1161002137,40.732000,-81.098120,McDonald's,44657,OH,"http://www.mcdonalds.com,http://www.mcdonalds...."
29,3211 S 4th St,Leavenworth,US,us/ks/leavenworth/3211s4thst/1780593795,39.285320,-94.904410,SONIC Drive In,66048,KS,https://locations.sonicdrivein.com/ks/leavenwo...
...,...,...,...,...,...,...,...,...,...,...
9970,15900 Hickman Rd,Clive,US,us/ia/clive/15900hickmanrd/-791445730,41.614430,-93.836650,Wendy's,50325,IA,"http://www.wendys.com,http://wendys.com"
9971,1199 Riverside Dr,Welch,US,us/wv/welch/1199riversidedr/-66712705,37.415662,-81.587851,Pizza Hut,24801,WV,http://pizzahut.com
9972,4025 Mapleshade Ln,Plano,US,us/tx/plano/4025mapleshadeln/1780593795,33.003138,-96.769369,SONIC Drive In,75093,TX,https://locations.sonicdrivein.com/tx/plano/40...
9973,31122 Fm 2920 Rd,Waller,US,"us/tx/waller/31122fm2920rd/1780593795,us/tx/wa...",30.060990,-95.911640,Sonic Drive-In,77484-8009,TX,https://locations.sonicdrivein.com/tx/waller/3...
9974,2830 S Douglas Blvd,Oklahoma City,US,us/ok/oklahomacity/2830sdouglasblvd/106088,35.434200,-97.370700,KFC,73130,OK,"http://www.kfc.com,http://kfc.com"
9975,8558 Lee Hwy,Fairfax,US,us/va/fairfax/8558leehwy/-891525969,38.873698,-77.240837,Subway,22031,VA,http://www.subway.com
9976,170 E Taylor St,San Jose,US,us/ca/sanjose/170etaylorst/1412731209,37.350692,-121.896548,El Tarasco Mexican Food,95112,CA,NaN
9977,6201 Lapalco Blvd,Marrero,US,us/la/marrero/6201lapalcoblvd/-2061630068,29.875182,-90.114028,Burger King,70072,LA,https://locations.bk.com/la/marrero/6201-lapal...
9978,Us Hwy 29,Chatham,US,us/va/chatham/ushwy29/-1161002137,36.789794,-79.394511,Mcdonald's,24531,VA,NaN
9979,50 New Orleans Rd,Hilton Head Island,US,us/sc/hiltonheadisland/50neworleansrd/-1161002137,32.155760,-80.759810,McDonald's,29928,SC,"http://mcdonalds.com,http://www.mcdonalds.com/..."
9980,10300 Little Patuxent Pkwy,Columbia,US,us/md/columbia/10300littlepatuxentpkwy/387392632,39.216640,-76.857860,Sarku Japan,21044,MD,"http://sarkujapan.com,http://www.sarkujapan.com"
9981,789 1st St S E,Saint Petersburg,US,us/fl/saintpetersburg/7891ststse/-345832572,27.762517,-82.634768,Chick-fil-a,33701,FL,NaN
9982,3020 E Sunshine St,Springfield,US,us/mo/springfield/3020esunshinest/-2061630068,37.180230,-93.234476,Burger King,65804,MO,http://bk.com
9983,7920 Cambridge Commons Dr,Charlotte,US,us/nc/charlotte/7920cambridgecommonsdr/-791445730,35.251244,-80.657136,Wendy's,28215,NC,"http://www.wendys.com,http://wendys.com"
9984,7100 Coastal Palms Blvd,Panama City,US,us/fl/panamacity/7100coastalpalmsblvd/-2061630068,30.175100,-85.760600,Burger King,32408,FL,"http://www.bk.com,https://locations.bk.com/fl/..."
9985,820 City Park Ave,Fort Collins,US,us/co/fortcollins/820cityparkave/-1161002137,40.575320,-105.100387,McDonalds,80521,CO,http://mcdonalds.com
9986,957 Battlefield Blvd N,Chesapeake,US,us/va/chesapeake/957battlefieldblvdn/-791445730,36.754430,-76.247670,Wendy's,23320,VA,http://www.wendys.com
9987,325 Main St,Adamsville,US,us/tn/adamsville/325mainst/1780593795,35.224293,-88.248200,Sonic Drive-in,38310,TN,http://sonicdrivein.com
9988,8 Easton Ave,New Brunswick,US,us/nj/newbrunswick/8eastonave/-1947870258,40.496880,-74.446976,Jimmy John's,8901,NJ,"http://www.jimmyjohns.com,http://jimmyjohns.com"
9989,1120 S Haynes Ave,Miles City,US,us/mt/milescity/1120shaynesave/-1161002137,46.397680,-105.822520,McDonald's,59301,MT,"http://mcdonalds.com,http://www.mcdonalds.com/..."
9990,6910 Ritchie Hwy,Glen Burnie,US,us/md/glenburnie/6910ritchiehwy/-791445730,39.186102,-76.612795,Wendy's,21061,MD,http://www.wendys.com
9991,1122 SE Hawthorne Blvd,Portland,US,us/or/portland/1122sehawthorneblvd/-2013151130,45.512000,-122.653960,"Burgerville, USA",97214,OR,http://www.burgerville.com
9992,310 Daniel Webster Hwy,Nashua,US,us/nh/nashua/310danielwebsterhwy/387392632,42.701994,-71.440706,Sarku Japan,3060,NH,http://www.sarkujapan.com
9993,3956 Guthrie St,East Chicago,US,us/in/eastchicago/3956guthriest/-477036959,41.640760,-87.433727,White Castle,46312,IN,"http://www.whitecastle.com,http://whitecastle.com"
9994,3823 Guess Rd,Durham,US,us/nc/durham/3823guessrd/2001384123,36.058624,-78.930378,Italian Pizzeria Restaurant,27705,NC,"http://www.durhamncpizza.com,http://durhamncpi..."
9995,3013 Peach Orchard Rd,Augusta,US,us/ga/augusta/3013peachorchardrd/-791445730,33.415257,-82.024531,Wendy's,30906,GA,"http://www.wendys.com,http://wendys.com"
9996,678 Northwest Hwy,Cary,US,us/il/cary/678northwesthwy/787691191,42.217300,-88.255800,Lee's Oriental Martial Arts,60013,IL,http://www.mcdonalds.com
9997,1708 Main St,Longmont,US,us/co/longmont/1708mainst/-448666054,40.189190,-105.101720,Five Guys,80501,CO,http://fiveguys.com
9998,67740 Highway 111,Cathedral City,US,us/ca/cathedralcity/67740highway111/-981164808,33.788640,-116.482150,El Pollo Loco,92234,CA,"http://www.elpolloloco.com,http://elpolloloco.com"
9999,5701 E La Palma Ave,Anaheim,US,us/ca/anaheim/5701elapalmaave/554191587,33.860074,-117.789762,Carl's Jr.,92807,CA,http://www.carlsjr.com

In [28]:
# Group and count number of fastfood restaurants by state:

fastfood_df2=fastfood_df.groupby('province', as_index=False).count()
fastfood_df2.head()

,province,address,city,country,keys,latitude,longitude,name,postalCode,websites
0,AK,14,14,14,14,14,14,14,14,13
1,AL,236,236,236,236,236,236,236,236,226
2,AR,151,151,151,151,151,151,151,151,145
3,AZ,208,208,208,208,208,208,208,208,198
4,CA,676,676,676,676,676,676,676,676,618

In [29]:
# Import population by state:

population = "Resources/US_population_2018.csv"
population = pd.read_csv(population)
population.head()

   Unnamed: 0         state  rank_state  estimated_pop_2019  perc_pop_2018
0           0    California           1            39865590          12.01
1           1         Texas           2            29206997           8.80
2           2       Florida           3            21299325           6.44
3           3      New York           4            19542209           5.91
4           4  Pennsylvania           5            12807060           3.87

In [30]:
#Push population to database under table name: population:

population.to_sql(name='population', con=engine, if_exists='append', index=False)

In [31]:
# Import state and the corresponding abbreviation. 
# Rename the abbreviation column to "provice" so that it can be joined with population:

state = "Resources/stateabb.csv"
state = pd.read_csv(state)
state.columns=["state","province"]
state.head()

      state province
0   Alabama       AL
1    Alaska       AK
2     State      Abb
3   Arizona       AZ
4  Arkansas       AR

In [32]:
# Push state to database under table name: state:

state.to_sql(name='state', con=engine, if_exists='append', index=False)

In [33]:
# Show all table names that are available under fast_food_db:
engine.table_names()

['fastfood', 'population', 'state']

In [34]:
# Merge population and state by "state":

populate_by_state=pd.merge(population, state, on='state')
populate_by_state.head()

,Unnamed: 0,state,rank_state,estimated_pop_2019,perc_pop_2018,province
0,0,California,1,39865590,12.01,CA
1,1,Texas,2,29206997,8.80,TX
2,2,Florida,3,21299325,6.44,FL
3,3,New York,4,19542209,5.91,NY
4,4,Pennsylvania,5,12807060,3.87,PA

In [35]:
# Merge population_by_state from above with fastfood count by state:

fastfood_population=pd.merge(fastfood_df2, populate_by_state, on='province')
fastfood_population.head()

,province,address,city,country,keys,latitude,longitude,name,postalCode,websites,Unnamed: 0,state,rank_state,estimated_pop_2019,perc_pop_2018
0,AK,14,14,14,14,14,14,14,14,13,48,Alaska,48,737438,0.22
1,AL,236,236,236,236,236,236,236,236,226,23,Alabama,24,4887871,1.48
2,AR,151,151,151,151,151,151,151,151,145,33,Arkansas,33,3013825,0.91
3,AZ,208,208,208,208,208,208,208,208,198,13,Arizona,14,7171646,2.17
4,CA,676,676,676,676,676,676,676,676,618,0,California,1,39865590,12.01

In [36]:
# Sort and rank the result by state population 
# Select relevant columns and pick only the top 10 states by population

fastfood_population_sorted = fastfood_population[['state','city','rank_state','estimated_pop_2019','perc_pop_2018']].sort_values(by="rank_state")
top10=fastfood_population_sorted.head(10)
top10

             state  city  rank_state  estimated_pop_2019  perc_pop_2018
4       California   676           1            39865590          12.01
42           Texas   634           2            29206997           8.80
8          Florida   471           3            21299325           6.44
33        New York   269           4            19542209           5.91
37    Pennsylvania   283           5            12807060           3.87
13        Illinois   363           6            12741080           3.85
34            Ohio   543           7            11689442           3.53
9          Georgia   347           8            10519475           3.18
26  North Carolina   358           9            10383620           3.14
21        Michigan   251          10             9995915           3.02

In [40]:
fastfood_population_sorted.to_sql(name='fastfood_by_state_sorted', con=engine, if_exists='append', index=False)

In [39]:
# Sort the top10 result by decending order:

top10 = top10.sort_values('rank_state',ascending=False)
top10.rename(columns={'city':'count'}, inplace=True)
top10

             state  count  rank_state  estimated_pop_2019  perc_pop_2018
21        Michigan    251          10             9995915           3.02
26  North Carolina    358           9            10383620           3.14
9          Georgia    347           8            10519475           3.18
34            Ohio    543           7            11689442           3.53
13        Illinois    363           6            12741080           3.85
37    Pennsylvania    283           5            12807060           3.87
33        New York    269           4            19542209           5.91
8          Florida    471           3            21299325           6.44
42           Texas    634           2            29206997           8.80
4       California    676           1            39865590          12.01

In [21]:
import matplotlib.pyplot as plt; plt.rcdefaults()
import numpy as np
import matplotlib.pyplot as plt

state = top10["state"]
y_pos = np.arange(len(state))
count = top10["count"]

plt.barh(state, count, align='center', alpha=0.5)
plt.yticks(y_pos, state)
plt.ylabel('State')
plt.xlabel('Fast Food Restaurant Count')
plt.title('Fast Food Restaurant Count in Top 10 States by Population')

plt.show()